### ISSUE TITLE
NullPointerException reading a LAZ file

### ISSUE THREAD

**Issue by gwlucastrig** [mreutegg/laszip4j#61]
I just had a user post an Issue on the Tinfour Github project page reporting a NullPointerException when reading a version 1.4 LAZ file.   While Tinfour still uses your old version 0.5 API, I downloaded the latest version and got similar results.

This is the stack trace the user posted

ERROR: cannot open lasreaderlas with file name '/home/martin/fm/Tinfour/tile_-235000_-1227000.laz'
java.lang.NullPointerException: Cannot invoke "com.github.mreutegg.laszip4j.laslib.LASreader.inside_none()" because "reader" is null
	at com.github.mreutegg.laszip4j.LASReader$None.apply(LASReader.java:160)
	at com.github.mreutegg.laszip4j.LASReader.openReader(LASReader.java:108)
	at com.github.mreutegg.laszip4j.LASReader.access$100(LASReader.java:32)
	at com.github.mreutegg.laszip4j.LASReader$LASPointIterator.<init>(LASReader.java:116)
	at com.github.mreutegg.laszip4j.LASReader$LASPointIterator.<init>(LASReader.java:112)
	at com.github.mreutegg.laszip4j.LASReader.lambda$getPoints$3(LASReader.java:88)

He posted his LAZ file at 
https://drive.google.com/file/d/1rvUUxoxtTovfVt68CDmwrMr99vlG-gd1/view?usp=sharing

The API I am using to read the file is
   LASReader reader = new LASReader(file);
    for (LASPoint p : reader.getPoints()) {
	}

You can see the original issue report at https://github.com/gwlucastrig/Tinfour/issues/89

Thank you for your attention in this matter.

**Comment by gwlucastrig** [comment]
Thank you for fixing this so quickly.
